# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/prot_ds',
                'doc_host': 'https://Dzeiberg.github.io',
                'git_url': 'https://github.com/Dzeiberg/prot_ds',
                'lib_path': 'prot_ds'},
  'syms': {'prot_ds.core': {'prot_ds.core.foo': ('core.html#foo', 'prot_ds/core.py')}}}