# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% auto 0
__all__ = ['queryGene']

# %% ../00_core.ipynb 18
def queryGene(ensg,missenseOnly=True):
    """
    Query myvariant.info for all results relevant to the given ensembl gene id
    
    Required Arguments:
    - ensg : Ensembl Gene ID (e.g. ENSG00000160072)
    
    Optional Arugments:
    - missenseOnly : default True : whether to query only missense variants
    """
    q = f"cadd.gene.gene_id:{ensg}"
    if missenseOnly:
        q += "%20AND%20cadd.consdetail:missense"
    r = requests.get(f'https://myvariant.info/v1/query?q={q}&fetch_all=TRUE')
    if not r.status_code == 200:
        raise ValueError()
    queryResult = EasyDict(json.loads(r.text))
    queries = []
    querySucceeded = lambda q: ("success" not in q or q.success)
    while "_scroll_id" in queryResult and querySucceeded(queryResult):
        r = requests.get(f'https://myvariant.info/v1/query?scroll_id={queryResult._scroll_id}')
        queries.append(queryResult)
        if not r.status_code == 200:
            raise ValueError()
        queryResult = EasyDict(json.loads(r.text))
    if querySucceeded(queryResult):
        queries.append(queryResult)
    return queries
